name: build apk

on:
  workflow_dispatch:
  push:
    branches:
      - 8-compile-android

jobs:
  black:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: |
          cd ci
          docker compose run --rm -it android

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flet-android
          path: build/apk/app-release.apk
